### ISSUE TITLE
Spot instances: checkpoint paths for intermediate data?

### ISSUE THREAD

**Issue by dav009** [aws/sagemaker-tensorflow-training-toolkit#346]
I am confused by the documentation. 

- I am using tensorflow with keras and spot instances.

- where should my model save checkpoints? 
- where should it read the checkpoints from to resume in case it was stopped at a previous point?

so far I have read docs mentioning: SM_OUTPUT_INTERMEDIATE_DIR,  passing `checkpoint_local_path` as an estimator parameter,  or using `/opt/ml/checkpoints/`[2]?

- when I try using `/opt/ml/checkpoints/` checkpoints are saved and syncrhonized but caller script throws an exception at the end of training, same when I try to use `checkpoint_local_path` to another path.

- is `SM_OUTPUT_DATA_DIR` synchronized into the instance at the beggining of a task? cause docs in [2] suggests storing checkpoints there

there are multiple docs and I find it really confusing as they seem to point out to different locations.

[1] https://docs.aws.amazon.com/sagemaker/latest/dg/model-checkpoints.html
[2] https://sagemaker.readthedocs.io/en/stable/using_tf.html#prepare-a-script-mode-training-script

**Comment by laurenyu** [comment]
sorry for the delayed response here - because TensorFlow (the framework itself) has its own checkpointing functionality, it currently does not use SageMaker's checkpoint directory by default. if you're using distributed training with parameter servers, then checkpoints are saved in S3; if you're using Horovod, then checkpoints are saved in `/opt/ml/model`.

If you're not relying on one of those two setups from the prebuilt SageMaker TensorFlow image, then you can save your model where you want, as long as your script is consistent about it.

you can read more [at this link under "model_dir"](https://sagemaker.readthedocs.io/en/stable/sagemaker.tensorflow.html#sagemaker.tensorflow.estimator.TensorFlow)
